// Elun 도시 DB — 단일 정본 (start.html · report.html · couple.html 공유)
// [name, country, longitude, IANA timezone] — tz가 역사적 DST까지 결정하므로 IANA 정확성 필수
// (Phoenix=DST 없음, Detroit/Indianapolis=자체 존 — America/New_York 등으로 뭉개지 말 것)
window.ELUN_CITIES = [
  // Korea · Japan
  ["Seoul","South Korea",126.98,"Asia/Seoul"],
  ["Busan","South Korea",129.08,"Asia/Seoul"],
  ["Incheon","South Korea",126.71,"Asia/Seoul"],
  ["Daegu","South Korea",128.60,"Asia/Seoul"],
  ["Gwangju","South Korea",126.85,"Asia/Seoul"],
  ["Daejeon","South Korea",127.38,"Asia/Seoul"],
  ["Tokyo","Japan",139.69,"Asia/Tokyo"],
  ["Osaka","Japan",135.50,"Asia/Tokyo"],
  // Greater China · SE Asia · India · Middle East
  ["Beijing","China",116.41,"Asia/Shanghai"],
  ["Shanghai","China",121.47,"Asia/Shanghai"],
  ["Hong Kong","Hong Kong",114.17,"Asia/Hong_Kong"],
  ["Taipei","Taiwan",121.56,"Asia/Taipei"],
  ["Singapore","Singapore",103.82,"Asia/Singapore"],
  ["Bangkok","Thailand",100.50,"Asia/Bangkok"],
  ["Ho Chi Minh City","Vietnam",106.63,"Asia/Ho_Chi_Minh"],
  ["Manila","Philippines",120.98,"Asia/Manila"],
  ["Jakarta","Indonesia",106.85,"Asia/Jakarta"],
  ["Mumbai","India",72.88,"Asia/Kolkata"],
  ["New Delhi","India",77.21,"Asia/Kolkata"],
  ["Dubai","UAE",55.27,"Asia/Dubai"],
  // USA — East
  ["New York","USA",-74.01,"America/New_York"],
  ["Boston","USA",-71.06,"America/New_York"],
  ["Philadelphia","USA",-75.17,"America/New_York"],
  ["Washington DC","USA",-77.04,"America/New_York"],
  ["Baltimore","USA",-76.61,"America/New_York"],
  ["Pittsburgh","USA",-80.00,"America/New_York"],
  ["Charlotte","USA",-80.84,"America/New_York"],
  ["Raleigh","USA",-78.64,"America/New_York"],
  ["Durham","USA",-78.90,"America/New_York"],
  ["Atlanta","USA",-84.39,"America/New_York"],
  ["Miami","USA",-80.19,"America/New_York"],
  ["Orlando","USA",-81.38,"America/New_York"],
  ["Tampa","USA",-82.46,"America/New_York"],
  ["Columbus","USA",-83.00,"America/New_York"],
  ["Cincinnati","USA",-84.51,"America/New_York"],
  ["Detroit","USA",-83.05,"America/Detroit"],
  ["Indianapolis","USA",-86.16,"America/Indiana/Indianapolis"],
  // USA — Central
  ["Chicago","USA",-87.63,"America/Chicago"],
  ["Houston","USA",-95.37,"America/Chicago"],
  ["Austin","USA",-97.74,"America/Chicago"],
  ["Dallas","USA",-96.80,"America/Chicago"],
  ["San Antonio","USA",-98.49,"America/Chicago"],
  ["Nashville","USA",-86.78,"America/Chicago"],
  ["New Orleans","USA",-90.07,"America/Chicago"],
  ["Minneapolis","USA",-93.27,"America/Chicago"],
  ["St. Louis","USA",-90.20,"America/Chicago"],
  ["Kansas City","USA",-94.58,"America/Chicago"],
  ["Milwaukee","USA",-87.91,"America/Chicago"],
  // USA — Mountain · West
  ["Denver","USA",-104.99,"America/Denver"],
  ["Salt Lake City","USA",-111.89,"America/Denver"],
  ["Phoenix","USA",-112.07,"America/Phoenix"],
  ["Las Vegas","USA",-115.14,"America/Los_Angeles"],
  ["Los Angeles","USA",-118.24,"America/Los_Angeles"],
  ["San Diego","USA",-117.16,"America/Los_Angeles"],
  ["San Francisco","USA",-122.42,"America/Los_Angeles"],
  ["San Jose","USA",-121.89,"America/Los_Angeles"],
  ["Sacramento","USA",-121.49,"America/Los_Angeles"],
  ["Portland","USA",-122.68,"America/Los_Angeles"],
  ["Seattle","USA",-122.33,"America/Los_Angeles"],
  ["Honolulu","USA",-157.86,"Pacific/Honolulu"],
  ["Anchorage","USA",-149.90,"America/Anchorage"],
  // Canada
  ["Toronto","Canada",-79.38,"America/Toronto"],
  ["Montreal","Canada",-73.57,"America/Toronto"],
  ["Vancouver","Canada",-123.12,"America/Vancouver"],
  ["Calgary","Canada",-114.07,"America/Edmonton"],
  // Europe
  ["London","UK",-0.13,"Europe/London"],
  ["Manchester","UK",-2.24,"Europe/London"],
  ["Dublin","Ireland",-6.26,"Europe/Dublin"],
  ["Paris","France",2.35,"Europe/Paris"],
  ["Berlin","Germany",13.40,"Europe/Berlin"],
  ["Munich","Germany",11.58,"Europe/Berlin"],
  ["Madrid","Spain",-3.70,"Europe/Madrid"],
  ["Barcelona","Spain",2.17,"Europe/Madrid"],
  ["Rome","Italy",12.50,"Europe/Rome"],
  ["Amsterdam","Netherlands",4.90,"Europe/Amsterdam"],
  ["Zurich","Switzerland",8.54,"Europe/Zurich"],
  ["Stockholm","Sweden",18.07,"Europe/Stockholm"],
  ["Warsaw","Poland",21.01,"Europe/Warsaw"],
  ["Moscow","Russia",37.62,"Europe/Moscow"],
  ["Istanbul","Turkey",28.98,"Europe/Istanbul"],
  // Oceania · LatAm · Africa
  ["Sydney","Australia",151.21,"Australia/Sydney"],
  ["Melbourne","Australia",144.96,"Australia/Melbourne"],
  ["Brisbane","Australia",153.03,"Australia/Brisbane"],
  ["Perth","Australia",115.86,"Australia/Perth"],
  ["Auckland","New Zealand",174.76,"Pacific/Auckland"],
  ["São Paulo","Brazil",-46.63,"America/Sao_Paulo"],
  ["Buenos Aires","Argentina",-58.38,"America/Argentina/Buenos_Aires"],
  ["Mexico City","Mexico",-99.13,"America/Mexico_City"],
  ["Bogotá","Colombia",-74.07,"America/Bogota"],
  ["Cairo","Egypt",31.24,"Africa/Cairo"],
  ["Lagos","Nigeria",3.39,"Africa/Lagos"],
  ["Johannesburg","South Africa",28.05,"Africa/Johannesburg"],
];
